import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
}

Properties props = buildUtils.loadProperties('publish.properties')

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

repositories {
    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    def includeImpl = { dep ->
        include(dep)
        implementation(dep)
    }

    includeImpl(libs.kibu.hook.api)
    includeImpl(libs.kibu.access.lib)
    includeImpl(libs.kibu.hooks)
    includeImpl(libs.kibu.fabric.hooks)
    includeImpl(libs.kibu.translation.api)
    includeImpl(libs.kibu.behaviour.api)
    includeImpl(libs.fabric.permissions.api)

    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
    testImplementation(libs.junit.jupiter.params)
    testImplementation(libs.fabric.loader.junit)
}

test {
    useJUnitPlatform()
}

processResources {
    def tokens = [
            "version": project.version.toString(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": javaVersion.toString()
    ]

    inputs.properties(tokens)

    filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.set(javaVersion)
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] $project.name $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Ruler'
                description = 'A Fabric mod for configuring rules for your Minecraft world. '
            }
        }
    }

    buildUtils.setupPublishRepository(repositories, props)
}