[versions]
minecraft = "26.2"
fabric-api = "0.152.2+26.2"
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
gradle-build-tools = "1.7.0"
java = "25"
kibu-hook-api = "1.5.0"
kibu-access-lib = "0.18.0+26.2"
kibu-hooks = "0.64.1+26.2"
kibu-fabric-hooks = "0.5.1+26.2"
kibu-translation-api = "0.27.0+26.2"
kibu-behaviour-api = "0.1.0+26.2"
fabric-permissions-api = "0.7.0"
junit = "5.9.2"

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
gradle-build-utils = { id = "gradle-build-utils", version.ref = "gradle-build-tools" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
kibu-hook-api = { module = "work.lclpnet.mods.kibu:kibu-hook-api", version.ref = "kibu-hook-api" }
kibu-access-lib = { module = "work.lclpnet.mods.kibu:kibu-access-lib", version.ref = "kibu-access-lib" }
kibu-hooks = { module = "work.lclpnet.mods.kibu:kibu-hooks", version.ref = "kibu-hooks" }
kibu-fabric-hooks = { module = "work.lclpnet.mods.kibu:kibu-fabric-hooks", version.ref = "kibu-fabric-hooks" }
kibu-translation-api = { module = "work.lclpnet.mods.kibu:kibu-translation-api", version.ref = "kibu-translation-api" }
kibu-behaviour-api = { module = "work.lclpnet.mods.kibu:kibu-behaviour-api", version.ref = "kibu-behaviour-api" }
fabric-permissions-api = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions-api" }
fabric-loader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
